- name: My first playbook
  hosts: all
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Create a file
      ansible.builtin.file:
        path: /home/ubuntu/test.txt
        state: touch